# Generated by Django 5.0.3 on 2024-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0002_resources_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_data',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
