# Generated by Django 5.0.3 on 2024-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0003_resources_data_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='folder',
            field=models.ImageField(default=1, upload_to='resources/folder', verbose_name='folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='logo',
            field=models.ImageField(upload_to='resources/category', verbose_name='File'),
        ),
    ]
