# Generated by Django 5.0.3 on 2024-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0004_resources_folder_alter_resources_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_data',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Folder', 'Folder')], default=1, max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
