# Generated by Django 5.0.3 on 2024-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0005_resources_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='resources_data',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
