# Generated by Django 5.0.3 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0006_alter_resources_title_alter_resources_data_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_data',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Folder', 'Folder'), ('Videos', 'Videos')], max_length=50, verbose_name='Type'),
        ),
    ]
