# Generated by Django 5.0.3 on 2024-07-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_dashboard', '0007_alter_resources_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources_file_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('data', models.CharField(max_length=500, verbose_name='Github Link')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_dashboard.resources', verbose_name='Resources')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_Folder_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('data', models.CharField(max_length=500, verbose_name='Github Link')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_dashboard.resources', verbose_name='Resources')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_video_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('data', models.CharField(max_length=500, verbose_name='Github Link')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_dashboard.resources', verbose_name='Resources')),
            ],
        ),
        migrations.DeleteModel(
            name='Resources_data',
        ),
    ]
