# Generated by Django 5.0.3 on 2024-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpostimage_blogposttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quoteauthor',
            field=models.CharField(default=1, max_length=50, verbose_name='Quote Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quotes',
            field=models.TextField(default=1, verbose_name='Quote'),
            preserve_default=False,
        ),
    ]
