# Generated by Django 5.0.3 on 2024-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_quoteauthor_blogpost_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='quoteauthor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quote Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='quotes',
            field=models.TextField(blank=True, null=True, verbose_name='Quote'),
        ),
    ]
