# Generated by Django 5.0.3 on 2024-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=1, max_length=50, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(default=1, max_length=50, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default=1, max_length=50, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default=1, upload_to='user/profile', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
