# Generated by Django 5.0.3 on 2024-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile_gender_profile_mobileno_profile_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='assets/images/profile_blank.png', upload_to='user/profile', verbose_name='Profile'),
        ),
    ]
