# Generated by Django 5.0.3 on 2024-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='assets/images/profile_blank.png', null=True, upload_to='user/profile', verbose_name='Profile'),
        ),
    ]
