# Generated by Django 5.0.3 on 2024-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='des',
            field=models.TextField(default=1, verbose_name='Short description'),
            preserve_default=False,
        ),
    ]
