# Generated by Django 5.0.3 on 2024-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_benefits_service_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_work',
            name='slno',
            field=models.CharField(default=1, max_length=50, verbose_name='Serial no'),
            preserve_default=False,
        ),
    ]
