# Generated by Django 5.0.3 on 2024-06-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_work_slno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_work',
            name='work',
            field=models.CharField(max_length=250, verbose_name='work'),
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=250, verbose_name='Solution')),
                ('des', models.CharField(max_length=2250, verbose_name='des')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='service')),
            ],
        ),
    ]
