# Generated by Django 5.0.3 on 2024-06-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_work_work_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bannerimg',
        ),
    ]
