# Generated by Django 5.0.3 on 2024-06-06 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Title')),
                ('img', models.ImageField(upload_to='Service/card', verbose_name='Service image')),
                ('bannerimg', models.ImageField(upload_to='Service/banner', verbose_name='Service banner image')),
                ('approach', ckeditor.fields.RichTextField(verbose_name='Approach')),
            ],
        ),
    ]
