# Generated by Django 5.0.3 on 2024-06-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
