# Generated by Django 5.0.3 on 2024-06-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projectfeedback_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfeedback',
            name='slug',
        ),
    ]
