# Generated by Django 5.0.3 on 2024-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_projectfeedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('img', models.ImageField(upload_to='team', verbose_name='Profile')),
                ('linkedin', models.CharField(blank=True, max_length=250, null=True, verbose_name='Linkedin Url')),
                ('instagram', models.CharField(blank=True, max_length=250, null=True, verbose_name='instagram Url')),
                ('twitter', models.CharField(blank=True, max_length=250, null=True, verbose_name='twitter Url')),
            ],
        ),
    ]
