# Generated by Django 5.0.3 on 2024-07-29 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_and_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
