# Generated by Django 5.0.3 on 2024-07-29 12:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_ads_horizontal_ads_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
