# Generated by Django 5.0.3 on 2024-07-30 16:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
