# Generated by Django 5.0.3 on 2024-06-06 16:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('shortdes', models.CharField(max_length=350, verbose_name='Short Description')),
                ('bannerimg', models.ImageField(upload_to='project/banner/', verbose_name='Banner Image')),
                ('cardimg', models.ImageField(upload_to='project/card/', verbose_name='Banner Image')),
                ('client', models.CharField(max_length=250, verbose_name='Client name')),
                ('hq', models.CharField(max_length=250, verbose_name='HeadQuaters')),
                ('industry', models.CharField(max_length=250, verbose_name='Industry')),
                ('founder', models.CharField(max_length=250, verbose_name='Founders')),
                ('service', models.CharField(max_length=250, verbose_name='Service')),
                ('time', models.CharField(max_length=250, verbose_name='Time Spent')),
                ('overview', ckeditor.fields.RichTextField(verbose_name='overview')),
                ('challenges', ckeditor.fields.RichTextField(verbose_name='challenges')),
                ('result', ckeditor.fields.RichTextField(verbose_name='result')),
                ('link', models.CharField(max_length=2250, verbose_name='Project Link')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('slug', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
