# Generated by Django 5.0.3 on 2024-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_experience_responsibilities_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='img',
            field=models.ImageField(default=1, upload_to='career/card', verbose_name='Card Image'),
            preserve_default=False,
        ),
    ]
