# Generated by Django 5.0.3 on 2024-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_career_stipend'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='des',
            field=models.TextField(default=1, verbose_name='Des'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='des',
            field=models.TextField(default=1, verbose_name='Des'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='des',
            field=models.TextField(default=1, verbose_name='Des'),
            preserve_default=False,
        ),
    ]
