# Generated by Django 5.0.3 on 2024-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_experience_des_responsibilities_des_skill_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='shortdes',
            field=models.CharField(default=1, max_length=250, verbose_name='Short description'),
            preserve_default=False,
        ),
    ]
