# Generated by Django 5.0.3 on 2024-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='email',
            field=models.CharField(default=1, max_length=250, verbose_name='Email ID'),
            preserve_default=False,
        ),
    ]
