# Generated by Django 5.0.3 on 2024-07-16 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_certificate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=250, verbose_name='Email ID')),
                ('date_of_issue', models.DateField(default=django.utils.timezone.now)),
                ('certificate_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('certificate_image', models.CharField(blank=True, max_length=250, null=True)),
                ('internship_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
        ),
    ]
