# Generated by Django 5.0.3 on 2024-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_offerletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
