# Generated by Django 5.0.3 on 2024-07-17 12:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_internshipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('des', ckeditor.fields.RichTextField(verbose_name='Short description')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50, verbose_name='Mode')),
                ('long_desc', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('img', models.ImageField(upload_to='training', verbose_name='Banner Image')),
            ],
        ),
    ]
