# Generated by Django 5.0.3 on 2024-07-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_speacial_training_training_faq_training_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.CharField(default=1, max_length=50, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
