# Generated by Django 5.0.3 on 2024-07-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0018_career_no_of_weeks_internship_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('report', models.TextField()),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('internship_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.internship_assigned')),
            ],
        ),
    ]
