# Generated by Django 5.0.3 on 2024-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0022_certificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(default=1, verbose_name='Is Completed'),
            preserve_default=False,
        ),
    ]
