# Generated by Django 5.0.3 on 2024-07-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0023_internship_assigned_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_assigned',
            name='offer_letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='career.offerletter', verbose_name='Offerletter'),
            preserve_default=False,
        ),
    ]
