# Generated by Django 5.0.3 on 2024-07-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0024_internship_assigned_offer_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_assigned',
            name='offer_letter',
        ),
    ]
