# Generated by Django 5.0.3 on 2024-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0027_projectreport_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_assigned',
            name='assigned_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='assigned_id'),
        ),
    ]
