# Generated by Django 5.0.3 on 2024-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0028_internship_assigned_assigned_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='submission',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rewrite', 'Rewrite'), ('Rejected', 'Rejected')], default='Pending', max_length=50, verbose_name='Submision'),
        ),
    ]
