# Generated by Django 5.0.3 on 2024-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0029_alter_projectreport_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_task_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
            ],
        ),
    ]
