# Generated by Django 5.0.3 on 2024-07-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0030_internship_task_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_task_week',
            name='internship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Internship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship_task_week',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
