# Generated by Django 5.0.3 on 2024-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0031_internship_task_week_internship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email',
            field=models.CharField(blank=True, max_length=250, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
