# Generated by Django 5.0.3 on 2024-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0032_alter_certificate_email_alter_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(verbose_name='if Ongoing the True '),
        ),
    ]
