# Generated by Django 5.0.3 on 2024-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0033_alter_certificate_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='if Ongoing the True '),
        ),
    ]
