# Generated by Django 5.0.3 on 2024-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0034_alter_internship_assigned_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(verbose_name='if Ongoing the True '),
        ),
    ]
