# Generated by Django 5.0.3 on 2024-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0036_alter_internship_assigned_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Completed'),
        ),
    ]
