# Generated by Django 5.0.3 on 2024-07-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0038_rename_completed_internship_assigned_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship_assigned',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
