# Generated by Django 5.0.3 on 2024-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0039_rename_is_completed_internship_assigned_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_assigned',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
